version: '3'

services:
  socca:
    build: .
    container_name: socca
    restart: unless-stopped
    volumes:
      - socca-data:/app/data
      - socca-logs:/app/logs
    env_file:
      - .env

volumes:
  socca-data:
  socca-logs: